import { Boss, BossType } from './types';

export const LEVELS: Boss[] = [
  {
    id: 1,
    name: "The Reaction Wizard",
    type: BossType.BASIC,
    maxHp: 400,
    icon: "flask",
    color: "text-green-400",
    timeLimit: 20,
    questions: [
      // Haloalkanes & Haloarenes, Alcohols, Phenols, Ethers
      { id: 101, text: "SN1 reaction intermediate?", options: ["Carbanion", "Free Radical", "Carbocation", "Transition State"], correctIndex: 2, damage: 75 },
      { id: 102, text: "Reagent for Lucas Test?", options: ["Conc. HCl + ZnCl2", "Dil. HCl + Zn", "Conc. H2SO4", "Br2 + H2O"], correctIndex: 0, damage: 75 },
      { id: 103, text: "Phenol + Bromine water gives?", options: ["m-bromophenol", "2,4,6-tribromophenol", "o-bromophenol", "Bromobenzene"], correctIndex: 1, damage: 75 },
      { id: 104, text: "Williamson's synthesis makes?", options: ["Alcohols", "Ketones", "Ethers", "Aldehydes"], correctIndex: 2, damage: 75 },
      { id: 105, text: "Dehydration of ethanol at 443K?", options: ["Ethene", "Ethoxyethane", "Ethanal", "Ethane"], correctIndex: 0, damage: 80 },
      { id: 106, text: "Grignard reagent + CO2 gives?", options: ["Alcohol", "Carboxylic Acid", "Ketone", "Ester"], correctIndex: 1, damage: 80 },
      { id: 107, text: "Reimer-Tiemann reaction product?", options: ["Salicylaldehyde", "Salicylic Acid", "Phenol", "Benzaldehyde"], correctIndex: 0, damage: 80 },
      { id: 108, text: "Strongest Acid?", options: ["Ethanol", "Phenol", "o-Nitrophenol", "p-Nitrophenol"], correctIndex: 3, damage: 80 },
      { id: 109, text: "Wurtz reaction uses which metal?", options: ["Zn", "Na", "Mg", "Cu"], correctIndex: 1, damage: 75 },
      { id: 110, text: "Finkelstein reaction reactant?", options: ["R-Cl + NaI", "R-OH + HX", "R-X + AgF", "R-H + X2"], correctIndex: 0, damage: 75 },
      { id: 111, text: "Swarts reaction produces?", options: ["Alkyl Iodides", "Alkyl Fluorides", "Alkyl Bromides", "Alkyl Chlorides"], correctIndex: 1, damage: 75 },
      { id: 112, text: "Inversion of configuration occurs in?", options: ["SN1", "SN2", "E1", "E2"], correctIndex: 1, damage: 75 },
      { id: 113, text: "Which is a chiral molecule?", options: ["Butan-1-ol", "Butan-2-ol", "Propan-2-ol", "Ethanol"], correctIndex: 1, damage: 80 },
      { id: 114, text: "Equimolar mixture of enantiomers?", options: ["Racemic mixture", "Meso compound", "Diastereomer", "Pure enantiomer"], correctIndex: 0, damage: 75 },
      { id: 115, text: "Fitting reaction involves?", options: ["Two Alkyl halides", "Two Aryl halides", "Alkyl + Aryl halide", "Alcohol + Acid"], correctIndex: 1, damage: 80 },
      { id: 116, text: "Oxidation of primary alcohol gives?", options: ["Ketone", "Aldehyde/Acid", "Ether", "Alkene"], correctIndex: 1, damage: 75 },
      { id: 117, text: "Cumene is used to prepare?", options: ["Phenol", "Toluene", "Aniline", "Benzene"], correctIndex: 0, damage: 80 },
      { id: 118, text: "Aspirin is acetylation of?", options: ["Phenol", "Salicylic Acid", "Benzoic Acid", "Benzaldehyde"], correctIndex: 1, damage: 80 },
      { id: 119, text: "Which test distinguishes 1°, 2°, 3° alcohols?", options: ["Lucas Test", "Tollens Test", "Fehling Test", "Iodoform Test"], correctIndex: 0, damage: 80 },
      { id: 120, text: "Diethyl ether structure?", options: ["R-O-R", "R-CO-R", "R-COOH", "R-CHO"], correctIndex: 0, damage: 70 },
      { id: 121, text: "Boiling point order?", options: ["R-Cl > R-Br > R-I", "R-I > R-Br > R-Cl", "R-Cl > R-I > R-Br", "All equal"], correctIndex: 1, damage: 75 },
      { id: 122, text: "DDT is prepared from?", options: ["Chlorobenzene + Chloral", "Benzene + Cl2", "Phenol + CCl4", "Toluene + Cl2"], correctIndex: 0, damage: 85 },
      { id: 123, text: "Which has highest dipole moment?", options: ["CH2Cl2", "CHCl3", "CCl4", "CH3Cl"], correctIndex: 3, damage: 80 },
      { id: 124, text: "Catalyst in Sandmeyer reaction?", options: ["Cu2Cl2", "Cu powder", "FeCl3", "ZnCl2"], correctIndex: 0, damage: 75 },
      { id: 125, text: "Which is gem-dihalide?", options: ["Ethylene dichloride", "Ethylidene chloride", "Trimethylene bromide", "None"], correctIndex: 1, damage: 80 },
      { id: 126, text: "Picric acid is?", options: ["2,4,6-Trinitrophenol", "Benzoic acid", "Salicylic acid", "Nitrobenzene"], correctIndex: 0, damage: 80 },
      { id: 127, text: "Product of Phenol + Zn dust?", options: ["Benzene", "Toluene", "Benzaldehyde", "Benzoic acid"], correctIndex: 0, damage: 75 },
      { id: 128, text: "Methanol poisoning antidote?", options: ["Ethanol", "Acetone", "Formaldehyde", "Water"], correctIndex: 0, damage: 85 },
      { id: 129, text: "Denatured spirit contains?", options: ["Ethanol + Pyridine", "Ethanol + Water", "Methanol only", "Pure Ethanol"], correctIndex: 0, damage: 75 },
      { id: 130, text: "Ether + HI (excess) gives?", options: ["Alcohol + Alkyl Iodide", "Two Alkyl Iodides", "Alkene + Iodine", "Ether + I2"], correctIndex: 1, damage: 85 },
      { id: 131, text: "Iodoform test checks for?", options: ["CH3-CO- group", "CH3-CH2- group", "COOH group", "NH2 group"], correctIndex: 0, damage: 80 },
      { id: 132, text: "Reactant for Kolbe's reaction?", options: ["Phenol + CO2", "Phenol + CHCl3", "Benzene + CO2", "Aniline + CO2"], correctIndex: 0, damage: 80 },
      { id: 133, text: "Product of Kolbe's reaction?", options: ["Salicylic acid", "Salicylaldehyde", "Benzoic acid", "Benzene"], correctIndex: 0, damage: 80 },
      { id: 134, text: "Hybridization of C in C-X bond?", options: ["sp3", "sp2", "sp", "dsp2"], correctIndex: 0, damage: 70 },
      { id: 135, text: "Allylic halide example?", options: ["3-chloroprop-1-ene", "1-chloroprop-1-ene", "2-chloropropane", "Chlorobenzene"], correctIndex: 0, damage: 85 },
      { id: 136, text: "Propene + HBr (Peroxide effect)?", options: ["1-Bromopropane", "2-Bromopropane", "Propane", "Propyne"], correctIndex: 0, damage: 80 },
      { id: 137, text: "Which undergoes SN2 fastest?", options: ["1° Halide", "2° Halide", "3° Halide", "Aryl Halide"], correctIndex: 0, damage: 75 },
      { id: 138, text: "Which undergoes SN1 fastest?", options: ["3° Halide", "2° Halide", "1° Halide", "Methyl Halide"], correctIndex: 0, damage: 75 },
      { id: 139, text: "Best method for Alkyl Chloride?", options: ["Alcohol + SOCl2", "Alcohol + HCl", "Alcohol + PCl5", "Alcohol + PCl3"], correctIndex: 0, damage: 80 },
      { id: 140, text: "Chloroform kept in dark bottles?", options: ["Avoid oxidation to Phosgene", "Avoid evaporation", "Avoid reaction with glass", "It is light sensitive"], correctIndex: 0, damage: 80 }
    ]
  },
  {
    id: 2,
    name: "Electro Emperor",
    type: BossType.ELECTRO,
    maxHp: 550,
    icon: "zap",
    color: "text-blue-400",
    timeLimit: 18,
    questions: [
      // Electrochemistry, Solutions (Colligative properties)
      { id: 201, text: "Unit of molar conductivity?", options: ["S cm-1", "S cm2 mol-1", "S m-1", "S mol-1"], correctIndex: 1, damage: 80 },
      { id: 202, text: "Spontaneous cell reaction ΔG?", options: ["Positive", "Negative", "Zero", "Infinity"], correctIndex: 1, damage: 80 },
      { id: 203, text: "Charge to reduce 1 mol MnO4- to Mn2+?", options: ["1F", "3F", "5F", "7F"], correctIndex: 2, damage: 100 },
      { id: 204, text: "Fuel cell product?", options: ["Heat", "Electricity", "Light", "Sound"], correctIndex: 1, damage: 80 },
      { id: 205, text: "SHE potential?", options: ["1.0 V", "0.0 V", "-1.0 V", "0.1 V"], correctIndex: 1, damage: 80 },
      { id: 206, text: "Corrosion of iron is?", options: ["Oxidation", "Reduction", "Hydration", "Electrochemical phenomenon"], correctIndex: 3, damage: 80 },
      { id: 207, text: "Anode in Galvanic cell?", options: ["Positive", "Negative", "Neutral", "Unknown"], correctIndex: 1, damage: 80 },
      { id: 208, text: "Strongest reducing agent?", options: ["Li", "Na", "K", "F2"], correctIndex: 0, damage: 80 },
      { id: 209, text: "Kohlrausch law relates to?", options: ["Infinite dilution", "Concentrated solution", "Gases", "Solids"], correctIndex: 0, damage: 85 },
      { id: 210, text: "Lead storage battery anode?", options: ["Pb", "PbO2", "PbSO4", "H2SO4"], correctIndex: 0, damage: 85 },
      { id: 211, text: "Conductivity ___ with dilution?", options: ["Increases", "Decreases", "Remains same", "Fluctuates"], correctIndex: 1, damage: 85 },
      { id: 212, text: "Molar conductivity ___ with dilution?", options: ["Increases", "Decreases", "Remains same", "Fluctuates"], correctIndex: 0, damage: 85 },
      { id: 213, text: "Salt bridge function?", options: ["Connects circuit", "Generates voltage", "Increases resistance", "Stops reaction"], correctIndex: 0, damage: 80 },
      { id: 214, text: "Unit of cell constant?", options: ["cm", "cm-1", "cm2", "cm-2"], correctIndex: 1, damage: 80 },
      { id: 215, text: "Faraday's 1st Law formula?", options: ["w = ZIt", "w = ZI", "w = It/Z", "w = Z/It"], correctIndex: 0, damage: 85 },
      { id: 216, text: "Product at cathode (Molten NaCl)?", options: ["Na", "Cl2", "H2", "O2"], correctIndex: 0, damage: 85 },
      { id: 217, text: "Mercury cell is used in?", options: ["Cars", "Watches", "Inverters", "Spacecraft"], correctIndex: 1, damage: 80 },
      { id: 218, text: "Standard conditions for E0?", options: ["298K, 1M, 1 bar", "273K, 1M, 1 atm", "298K, 0.1M, 1 bar", "300K, 1M, 1 bar"], correctIndex: 0, damage: 80 },
      { id: 219, text: "Cathode in dry cell?", options: ["Zinc container", "Graphite rod", "MnO2", "NH4Cl"], correctIndex: 1, damage: 85 },
      { id: 220, text: "Overpotential is needed for?", options: ["Metal deposition", "Gas evolution", "Salt formation", "Heating"], correctIndex: 1, damage: 90 },
      { id: 221, text: "Van't Hoff factor for NaCl?", options: ["1", "2", "0.5", "3"], correctIndex: 1, damage: 75 },
      { id: 222, text: "Relative lowering of vapor pressure?", options: ["Mole fraction of solute", "Mole fraction of solvent", "Molality", "Molarity"], correctIndex: 0, damage: 80 },
      { id: 223, text: "Ebullioscopic constant is for?", options: ["Freezing point", "Boiling point", "Osmotic pressure", "Vapor pressure"], correctIndex: 1, damage: 80 },
      { id: 224, text: "Unit of Henry's Law constant?", options: ["atm", "mol/L", "L/mol", "Dimensionless"], correctIndex: 0, damage: 80 },
      { id: 225, text: "Azeotrope of 95% Ethanol?", options: ["Minimum boiling", "Maximum boiling", "Ideal solution", "Non-ideal"], correctIndex: 0, damage: 85 },
      { id: 226, text: "Osmotic pressure depends on?", options: ["Temperature only", "Concentration only", "Both T and C", "Pressure"], correctIndex: 2, damage: 80 },
      { id: 227, text: "Which is a colligative property?", options: ["Viscosity", "Surface tension", "Osmotic pressure", "Refractive index"], correctIndex: 2, damage: 75 },
      { id: 228, text: "Electrolyte in Lead Storage?", options: ["38% H2SO4", "Conc HCl", "NaOH", "KOH"], correctIndex: 0, damage: 85 },
      { id: 229, text: "Cell potential = ?", options: ["Ecathode - Eanode", "Eanode - Ecathode", "Ecathode + Eanode", "None"], correctIndex: 0, damage: 75 },
      { id: 230, text: "Reverse osmosis uses?", options: ["Semi-permeable membrane", "Filter paper", "Glass slab", "Copper mesh"], correctIndex: 0, damage: 80 },
      { id: 231, text: "Henry law: p = ?", options: ["KH * x", "KH / x", "x / KH", "KH + x"], correctIndex: 0, damage: 80 },
      { id: 232, text: "Maximum Van't Hoff factor?", options: ["Al2(SO4)3", "K2SO4", "NaCl", "Glucose"], correctIndex: 0, damage: 85 },
      { id: 233, text: "Ideal solution example?", options: ["Benzene + Toluene", "Ethanol + Water", "Acetone + Chloroform", "Phenol + Aniline"], correctIndex: 0, damage: 85 },
      { id: 234, text: "Positive deviation from Raoult Law?", options: ["Ethanol + Acetone", "Acetone + Chloroform", "Benzene + Toluene", "HCl + Water"], correctIndex: 0, damage: 85 },
      { id: 235, text: "Cryoscopic constant unit?", options: ["K kg mol-1", "K mol kg-1", "mol K kg-1", "g mol-1"], correctIndex: 0, damage: 90 },
      { id: 236, text: "Cathode protection metal for Iron?", options: ["Mg", "Cu", "Ag", "Pb"], correctIndex: 0, damage: 80 },
      { id: 237, text: "1 Faraday = ?", options: ["96500 C", "96000 C", "10000 C", "1.6x10^-19 C"], correctIndex: 0, damage: 70 },
      { id: 238, text: "Nernst Equation determines?", options: ["Equilibrium Constant", "Rate Constant", "Enthalpy", "Entropy"], correctIndex: 0, damage: 80 },
      { id: 239, text: "Rust formula?", options: ["Fe2O3.xH2O", "FeO", "Fe3O4", "Fe(OH)2"], correctIndex: 0, damage: 75 },
      { id: 240, text: "Isotonic solutions have same?", options: ["Osmotic pressure", "Density", "Volume", "Viscosity"], correctIndex: 0, damage: 80 }
    ]
  },
  {
    id: 3,
    name: "Organic Demon",
    type: BossType.ORGANIC,
    maxHp: 700,
    icon: "biohazard",
    color: "text-purple-400",
    timeLimit: 15,
    questions: [
      // Aldehydes, Ketones, Acids, Amines, Biomolecules, Polymers
      { id: 301, text: "Amide to Amine (1 less C)?", options: ["Gabriel Phthalimide", "Hoffmann Bromamide", "Carbylamine", "Wurtz"], correctIndex: 1, damage: 100 },
      { id: 302, text: "Distinguish Aldehydes?", options: ["Tollens' Reagent", "Lucas Reagent", "Hinsberg Reagent", "Baeyer's Reagent"], correctIndex: 0, damage: 100 },
      { id: 303, text: "Cannizzaro reaction reactant?", options: ["Acetaldehyde", "Acetone", "Formaldehyde", "Ethanol"], correctIndex: 2, damage: 100 },
      { id: 304, text: "Starch hydrolysis yields?", options: ["Fructose", "Glucose", "Galactose", "Sucrose"], correctIndex: 1, damage: 100 },
      { id: 305, text: "1° Amine + CHCl3 + KOH?", options: ["Cyanide", "Isocyanide", "Amide", "Nitro"], correctIndex: 1, damage: 120 },
      { id: 306, text: "Glucose functional group?", options: ["Ketone", "Aldehyde", "Ester", "Ether"], correctIndex: 1, damage: 100 },
      { id: 307, text: "Vitamin B12 metal?", options: ["Fe", "Co", "Zn", "Mg"], correctIndex: 1, damage: 100 },
      { id: 308, text: "Denaturation affects?", options: ["1° structure", "2° & 3° structure", "Only 2°", "Only 4°"], correctIndex: 1, damage: 100 },
      { id: 309, text: "Reduction of cyanide gives?", options: ["1° Amine", "2° Amine", "Amide", "Acid"], correctIndex: 0, damage: 100 },
      { id: 310, text: "Hinsberg reagent is?", options: ["Benzenesulphonyl chloride", "Benzoyl chloride", "Acetyl chloride", "Methyl chloride"], correctIndex: 0, damage: 100 },
      { id: 311, text: "Rosenmund reduction forms?", options: ["Aldehyde", "Alcohol", "Acid", "Ester"], correctIndex: 0, damage: 100 },
      { id: 312, text: "Clemmensen reduction reagent?", options: ["Zn-Hg/HCl", "NH2NH2/KOH", "LiAlH4", "NaBH4"], correctIndex: 0, damage: 110 },
      { id: 313, text: "Reagent for Wolff-Kishner?", options: ["Zn-Hg/HCl", "NH2NH2/KOH", "H2/Pd", "Sn/HCl"], correctIndex: 1, damage: 110 },
      { id: 314, text: "Aldol condensation requires?", options: ["Alpha-H", "Beta-H", "Gamma-H", "No Alpha-H"], correctIndex: 0, damage: 100 },
      { id: 315, text: "HVZ reaction forms?", options: ["Alpha-halo acid", "Beta-halo acid", "Acyl halide", "Acid anhydride"], correctIndex: 0, damage: 110 },
      { id: 316, text: "Basic strength in gas phase?", options: ["3° > 2° > 1° > NH3", "1° > 2° > 3° > NH3", "NH3 > 1° > 2° > 3°", "2° > 1° > 3° > NH3"], correctIndex: 0, damage: 110 },
      { id: 317, text: "Which base is not in DNA?", options: ["Adenine", "Guanine", "Cytosine", "Uracil"], correctIndex: 3, damage: 100 },
      { id: 318, text: "Glucose + HI gives?", options: ["n-Hexane", "Gluconic acid", "Saccharic acid", "Ethanol"], correctIndex: 0, damage: 100 },
      { id: 319, text: "Which is a Zwitter ion?", options: ["Amino Acid", "Carboxylic Acid", "Amine", "Alcohol"], correctIndex: 0, damage: 100 },
      { id: 320, text: "Acylation of amine gives?", options: ["Amide", "Salt", "Acid", "Isocyanide"], correctIndex: 0, damage: 100 },
      { id: 321, text: "Teflon monomer?", options: ["Tetrafluoroethene", "Ethene", "Vinyl Chloride", "Acrylonitrile"], correctIndex: 0, damage: 90 },
      { id: 322, text: "Nylon 6,6 monomers?", options: ["Adipic acid + Hexamethylenediamine", "Caprolactam", "Phenol + Formaldehyde", "Terephthalic acid + Glycol"], correctIndex: 0, damage: 95 },
      { id: 323, text: "Natural rubber is polymer of?", options: ["Isoprene", "Neoprene", "Chloroprene", "Styrene"], correctIndex: 0, damage: 90 },
      { id: 324, text: "Buna-S is?", options: ["Styrene-Butadiene", "Acrylonitrile-Butadiene", "Natural Rubber", "Polyester"], correctIndex: 0, damage: 90 },
      { id: 325, text: "Biodegradable polymer?", options: ["PHBV", "PVC", "Bakelite", "Polythene"], correctIndex: 0, damage: 95 },
      { id: 326, text: "Vitamin C is?", options: ["Ascorbic Acid", "Citric Acid", "Acetic Acid", "Tartaric Acid"], correctIndex: 0, damage: 85 },
      { id: 327, text: "Deficiency of Vit D?", options: ["Rickets", "Scurvy", "Beriberi", "Night Blindness"], correctIndex: 0, damage: 85 },
      { id: 328, text: "Sugar in RNA?", options: ["Ribose", "Deoxyribose", "Glucose", "Fructose"], correctIndex: 0, damage: 90 },
      { id: 329, text: "Peptide bond linkage?", options: ["-CO-NH-", "-CO-O-", "-NH-NH-", "-C-C-"], correctIndex: 0, damage: 90 },
      { id: 330, text: "Reaction: RCOOH + R'OH?", options: ["Esterification", "Saponification", "Neutralization", "Hydrolysis"], correctIndex: 0, damage: 85 },
      { id: 331, text: "Etard reaction gives?", options: ["Benzaldehyde", "Acetophenone", "Benzoic Acid", "Phenol"], correctIndex: 0, damage: 95 },
      { id: 332, text: "Gattermann-Koch reagent?", options: ["CO + HCl", "CO2 + HCl", "HCN + HCl", "Cl2 + Fe"], correctIndex: 0, damage: 95 },
      { id: 333, text: "Fehling A is?", options: ["Aq CuSO4", "Alk Na-K Tartrate", "AgNO3", "Cu2Cl2"], correctIndex: 0, damage: 90 },
      { id: 334, text: "Product of Aldol heating?", options: ["Alpha-beta unsaturated aldehyde", "Alcohol", "Acid", "Alkane"], correctIndex: 0, damage: 95 },
      { id: 335, text: "Stephen reaction reagent?", options: ["SnCl2 + HCl", "LiAlH4", "DIBAL-H", "Na + Ethanol"], correctIndex: 0, damage: 95 },
      { id: 336, text: "Strongest base in aqueous?", options: ["(CH3)2NH", "CH3NH2", "(CH3)3N", "NH3"], correctIndex: 0, damage: 100 },
      { id: 337, text: "Diazotization temp?", options: ["0-5°C", "20-25°C", "50-60°C", "100°C"], correctIndex: 0, damage: 90 },
      { id: 338, text: "Aniline + Bromine water?", options: ["2,4,6-Tribromoaniline", "o-Bromoaniline", "p-Bromoaniline", "Bromobenzene"], correctIndex: 0, damage: 95 },
      { id: 339, text: "Isocyanide smell?", options: ["Foul/Offensive", "Fruity", "Almond", "Pungent"], correctIndex: 0, damage: 85 },
      { id: 340, text: "Source of Iodine in body?", options: ["Thyroxine", "Insulin", "Adrenaline", "Hemoglobin"], correctIndex: 0, damage: 90 }
    ]
  },
  {
    id: 4,
    name: "Kinetics Overlord",
    type: BossType.KINETICS,
    maxHp: 850,
    icon: "flame",
    color: "text-orange-500",
    timeLimit: 15,
    questions: [
      // Chemical Kinetics, Surface Chemistry, General Principles
      { id: 401, text: "Zero order rate depends on?", options: ["Temperature", "Concentration", "Catalyst", "Surface Area"], correctIndex: 1, damage: 120 },
      { id: 402, text: "Impossible molecularity?", options: ["1", "2", "3", "Zero"], correctIndex: 3, damage: 120 },
      { id: 403, text: "First order 'k' unit?", options: ["mol L-1 s-1", "s-1", "L mol-1 s-1", "mol-1 s-1"], correctIndex: 1, damage: 120 },
      { id: 404, text: "Catalyst lowers?", options: ["Enthalpy", "Internal Energy", "Activation Energy", "Entropy"], correctIndex: 2, damage: 120 },
      { id: 405, text: "Gas on Solid adsorption?", options: ["Endothermic", "Exothermic", "Iso-enthalpic", "None"], correctIndex: 1, damage: 120 },
      { id: 406, text: "Arrhenius Equation?", options: ["k = A e^(-Ea/RT)", "k = A e^(Ea/RT)", "k = A e^(-RT/Ea)", "k = A - Ea/RT"], correctIndex: 0, damage: 120 },
      { id: 407, text: "Radioactive decay order?", options: ["Zero", "First", "Second", "Third"], correctIndex: 1, damage: 120 },
      { id: 408, text: "Inversion of cane sugar order?", options: ["Pseudo-first", "Second", "Zero", "Third"], correctIndex: 0, damage: 120 },
      { id: 409, text: "Unit of k for Zero order?", options: ["mol L-1 s-1", "s-1", "L mol-1 s-1", "Dimensionless"], correctIndex: 0, damage: 120 },
      { id: 410, text: "Slope of ln(k) vs 1/T?", options: ["-Ea/R", "Ea/R", "R/Ea", "-R/Ea"], correctIndex: 0, damage: 125 },
      { id: 411, text: "Collision frequency symbol?", options: ["Z", "A", "Ea", "P"], correctIndex: 0, damage: 120 },
      { id: 412, text: "Physisorption energy?", options: ["20-40 kJ/mol", "80-240 kJ/mol", "High", "Very High"], correctIndex: 0, damage: 120 },
      { id: 413, text: "Chemisorption is?", options: ["Reversible", "Irreversible", "Multi-layered", "Non-specific"], correctIndex: 1, damage: 120 },
      { id: 414, text: "Tyndall effect is shown by?", options: ["True solution", "Colloid", "Suspension", "Pure liquid"], correctIndex: 1, damage: 120 },
      { id: 415, text: "Movement of colloidal particles?", options: ["Brownian motion", "Tyndall effect", "Electrophoresis", "Dialysis"], correctIndex: 0, damage: 120 },
      { id: 416, text: "Charge on sol particles determined by?", options: ["Electrophoresis", "Dialysis", "Tyndall effect", "Peptization"], correctIndex: 0, damage: 125 },
      { id: 417, text: "Emulsion is?", options: ["Solid in Liquid", "Liquid in Liquid", "Liquid in Gas", "Gas in Liquid"], correctIndex: 1, damage: 120 },
      { id: 418, text: "Shape selective catalyst?", options: ["Zeolite", "Pt", "Fe", "V2O5"], correctIndex: 0, damage: 120 },
      { id: 419, text: "Process to remove ions from colloid?", options: ["Dialysis", "Peptization", "Coagulation", "Bredig's Arc"], correctIndex: 0, damage: 120 },
      { id: 420, text: "Freundlich isotherm valid at?", options: ["Low P", "High P", "Moderate P", "All P"], correctIndex: 2, damage: 125 },
      { id: 421, text: "Half life of 1st order?", options: ["0.693/k", "k/0.693", "1/k", "0.693k"], correctIndex: 0, damage: 120 },
      { id: 422, text: "Example of aerosol?", options: ["Fog", "Milk", "Butter", "Paint"], correctIndex: 0, damage: 115 },
      { id: 423, text: "Example of gel?", options: ["Butter", "Milk", "Fog", "Smoke"], correctIndex: 0, damage: 115 },
      { id: 424, text: "Example of solid sol?", options: ["Gemstone", "Paint", "Milk", "Fog"], correctIndex: 0, damage: 115 },
      { id: 425, text: "Hardy-Schulze rule?", options: ["Coagulation power", "Adsorption", "Catalysis", "Solubility"], correctIndex: 0, damage: 125 },
      { id: 426, text: "Flocculating power of Al3+ vs Na+?", options: ["Al3+ > Na+", "Na+ > Al3+", "Al3+ = Na+", "None"], correctIndex: 0, damage: 120 },
      { id: 427, text: "Enzyme for Sucrose -> Glucose?", options: ["Invertase", "Zymase", "Urease", "Diastase"], correctIndex: 0, damage: 120 },
      { id: 428, text: "Enzyme for Glucose -> Ethanol?", options: ["Zymase", "Invertase", "Pepsin", "Trypsin"], correctIndex: 0, damage: 120 },
      { id: 429, text: "Adsorption is a ___ phenomenon?", options: ["Surface", "Bulk", "Volume", "Colligative"], correctIndex: 0, damage: 115 },
      { id: 430, text: "For exothermic, adsorption ___ with Temp?", options: ["Decreases", "Increases", "Constant", "None"], correctIndex: 0, damage: 120 },
      { id: 431, text: "Protective colloid power measured by?", options: ["Gold Number", "Silver Number", "Avogadro Number", "Hardy Number"], correctIndex: 0, damage: 130 },
      { id: 432, text: "Cottrell precipitator removes?", options: ["Smoke/Carbon", "Water", "Gas", "Ions"], correctIndex: 0, damage: 120 },
      { id: 433, text: "Extent of adsorption (x/m) depends on?", options: ["Pressure", "Volume", "Density", "Color"], correctIndex: 0, damage: 115 },
      { id: 434, text: "Zone refining is for?", options: ["Si/Ge", "Fe", "Cu", "Al"], correctIndex: 0, damage: 125 },
      { id: 435, text: "Froth floatation is for?", options: ["Sulphide ores", "Oxide ores", "Carbonate ores", "Halide ores"], correctIndex: 0, damage: 120 },
      { id: 436, text: "Calcination involves heating in?", options: ["Absence of air", "Presence of air", "Water", "Vacuum"], correctIndex: 0, damage: 120 },
      { id: 437, text: "Roasting involves heating in?", options: ["Presence of air", "Absence of air", "Water", "H2 gas"], correctIndex: 0, damage: 120 },
      { id: 438, text: "Metal refined by Mond Process?", options: ["Ni", "Zr", "Ti", "Cu"], correctIndex: 0, damage: 125 },
      { id: 439, text: "Van Arkel method for?", options: ["Zr / Ti", "Ni", "Cu", "Fe"], correctIndex: 0, damage: 125 },
      { id: 440, text: "Blister copper contains?", options: ["SO2", "CO2", "O2", "H2"], correctIndex: 0, damage: 125 }
    ]
  },
  {
    id: 5,
    name: "Periodic Titan",
    type: BossType.FINAL,
    maxHp: 1200,
    icon: "atom",
    color: "text-pink-500",
    timeLimit: 12,
    questions: [
      // d & f Block, Coordination Compounds
      { id: 501, text: "Transition color cause?", options: ["f-f transition", "d-d transition", "p-d transition", "Charge transfer"], correctIndex: 1, damage: 150 },
      { id: 502, text: "Lanthanoid contraction cause?", options: ["Poor shielding of 4f", "5d electrons", "6s electrons", "4d electrons"], correctIndex: 0, damage: 160 },
      { id: 503, text: "[Ni(CN)4]2- geometry?", options: ["Tetrahedral", "Square Planar", "Octahedral", "Trigonal"], correctIndex: 1, damage: 160 },
      { id: 504, text: "EDTA denticity?", options: ["2", "4", "6", "1"], correctIndex: 2, damage: 160 },
      { id: 505, text: "Strongest Oxidizer?", options: ["Cr2O7 2-", "MnO4 -", "V2O5", "TiO2"], correctIndex: 1, damage: 200 },
      { id: 506, text: "Spin magnetic moment formula?", options: ["√n(n+2)", "√n(n+1)", "n(n+2)", "√2n(n+1)"], correctIndex: 0, damage: 150 },
      { id: 507, text: "Highest oxidation state of Mn?", options: ["+4", "+5", "+6", "+7"], correctIndex: 3, damage: 150 },
      { id: 508, text: "Ziegler-Natta catalyst use?", options: ["Hydrogenation", "Polymerization", "Oxidation", "Cracking"], correctIndex: 1, damage: 150 },
      { id: 509, text: "Brass is an alloy of?", options: ["Cu + Zn", "Cu + Sn", "Cu + Ni", "Zn + Pb"], correctIndex: 0, damage: 150 },
      { id: 510, text: "Bronze is an alloy of?", options: ["Cu + Zn", "Cu + Sn", "Cu + Ni", "Zn + Pb"], correctIndex: 1, damage: 150 },
      { id: 511, text: "Magnetic moment of Fe2+ (n=4)?", options: ["4.9 BM", "2.8 BM", "5.9 BM", "1.73 BM"], correctIndex: 0, damage: 160 },
      { id: 512, text: "Color of KMnO4 is due to?", options: ["d-d transition", "Charge transfer", "f-f transition", "Polarization"], correctIndex: 1, damage: 160 },
      { id: 513, text: "Pair with same size due to contraction?", options: ["Zr, Hf", "La, Lu", "Fe, Co", "Sc, Y"], correctIndex: 0, damage: 160 },
      { id: 514, text: "General config of d-block?", options: ["(n-1)d 1-10 ns 0-2", "ns 1-2", "np 1-6", "nd 1-10"], correctIndex: 0, damage: 150 },
      { id: 515, text: "Isomerism in [Co(NH3)5ONO]Cl2?", options: ["Linkage", "Ionization", "Coordination", "Geometrical"], correctIndex: 0, damage: 160 },
      { id: 516, text: "Isomerism in [Co(NH3)5Br]SO4?", options: ["Linkage", "Ionization", "Hydrate", "Optical"], correctIndex: 1, damage: 160 },
      { id: 517, text: "Strongest ligand?", options: ["Cl-", "H2O", "NH3", "CO"], correctIndex: 3, damage: 160 },
      { id: 518, text: "Hybridization of [Co(NH3)6]3+?", options: ["sp3d2", "d2sp3", "sp3", "dsp2"], correctIndex: 1, damage: 160 },
      { id: 519, text: "Common ox. state of Lanthanoids?", options: ["+2", "+3", "+4", "+5"], correctIndex: 1, damage: 150 },
      { id: 520, text: "Coinage metals?", options: ["Cu, Ag, Au", "Zn, Cd, Hg", "Fe, Co, Ni", "Ru, Rh, Pd"], correctIndex: 0, damage: 150 },
      { id: 521, text: "Shape of d-orbitals?", options: ["Spherical", "Dumbbell", "Double Dumbbell", "Complex"], correctIndex: 2, damage: 150 },
      { id: 522, text: "Which is diamagnetic?", options: ["Zn2+", "Cu2+", "Fe3+", "Mn2+"], correctIndex: 0, damage: 160 },
      { id: 523, text: "Catalyst for Contact Process?", options: ["V2O5", "Fe", "Pt", "Ni"], correctIndex: 0, damage: 150 },
      { id: 524, text: "Catalyst for Haber Process?", options: ["Fe", "V2O5", "Pt", "Cu"], correctIndex: 0, damage: 150 },
      { id: 525, text: "Interstitial compounds are?", options: ["Chemically reactive", "Chemically inert", "Soft", "Low melting"], correctIndex: 1, damage: 155 },
      { id: 526, text: "Oxidation state of Ni in Ni(CO)4?", options: ["0", "+2", "+4", "-2"], correctIndex: 0, damage: 160 },
      { id: 527, text: "Color of Cr2O7 2-?", options: ["Orange", "Yellow", "Green", "Purple"], correctIndex: 0, damage: 150 },
      { id: 528, text: "Color of CrO4 2-?", options: ["Yellow", "Orange", "Green", "Red"], correctIndex: 0, damage: 150 },
      { id: 529, text: "Most common Actinoid ox. state?", options: ["+3", "+4", "+5", "+6"], correctIndex: 0, damage: 150 },
      { id: 530, text: "Which is a bidentate ligand?", options: ["Oxalate", "Ammonia", "Water", "Chloride"], correctIndex: 0, damage: 155 },
      { id: 531, text: "Coordination number of Pt in [PtCl6]2-?", options: ["6", "4", "2", "8"], correctIndex: 0, damage: 150 },
      { id: 532, text: "F-block elements are called?", options: ["Inner Transition", "Transition", "Representative", "Noble"], correctIndex: 0, damage: 150 },
      { id: 533, text: "Element with max unpaired electrons?", options: ["Cr (3d5 4s1)", "Mn (3d5 4s2)", "Fe (3d6 4s2)", "Zn (3d10 4s2)"], correctIndex: 0, damage: 160 },
      { id: 534, text: "Which forms colorless ions?", options: ["Sc3+", "Ti3+", "V3+", "Cr3+"], correctIndex: 0, damage: 160 },
      { id: 535, text: "Wilkinson catalyst uses?", options: ["Rh", "Co", "Fe", "Pt"], correctIndex: 0, damage: 165 },
      { id: 536, text: "Primary valency in CoCl3.6NH3?", options: ["3", "6", "9", "1"], correctIndex: 0, damage: 155 },
      { id: 537, text: "Secondary valency in CoCl3.6NH3?", options: ["6", "3", "9", "1"], correctIndex: 0, damage: 155 },
      { id: 538, text: "Crystal Field Splitting energy order?", options: ["Sq. Planar > Oct > Tet", "Oct > Tet > Sq. Planar", "Tet > Oct > Sq. Planar", "All equal"], correctIndex: 0, damage: 170 },
      { id: 539, text: "Spectrochemical series bases on?", options: ["Field strength", "Size", "Electronegativity", "Mass"], correctIndex: 0, damage: 160 },
      { id: 540, text: "Amalgam is alloy with?", options: ["Hg", "Ag", "Au", "Sn"], correctIndex: 0, damage: 150 }
    ]
  }
];